name: Update Plugins

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  update_plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Update Plugins
        run: php bin/update-plugins.php

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'plugins/*.json'
          default_author: github_actor
          message: 'Automated plugins update'

      - name: Size?
        run: du -sh plugins
