name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Update Plugins
        run: php bin/update-plugins.php

      - name: Update Themes
        run: php bin/update-themes.php

      - name: Record version release dates
        run: php bin/update-releases.php

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: |
           - plugins
           - themes
           - plugin-releases.csv
           - theme-releases.csv
          default_author: github_actions
          message: 'Automated updates'

      - name: Size?
        run: du -sh plugins themes
